---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-inference-llmaz-io-v1alpha1-backendruntime
  failurePolicy: Fail
  name: mbackendruntime.kb.io
  rules:
  - apiGroups:
    - inference.llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backendruntimes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-llmaz-io-v1alpha1-openmodel
  failurePolicy: Fail
  name: mopenmodel.kb.io
  rules:
  - apiGroups:
    - llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openmodels
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-inference-llmaz-io-v1alpha1-playground
  failurePolicy: Fail
  name: mplayground.kb.io
  rules:
  - apiGroups:
    - inference.llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - playgrounds
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-inference-llmaz-io-v1alpha1-service
  failurePolicy: Fail
  name: mservice.kb.io
  rules:
  - apiGroups:
    - inference.llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-inference-llmaz-io-v1alpha1-backendruntime
  failurePolicy: Fail
  name: vbackendruntime.kb.io
  rules:
  - apiGroups:
    - inference.llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backendruntimes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-llmaz-io-v1alpha1-openmodel
  failurePolicy: Fail
  name: vopenmodel.kb.io
  rules:
  - apiGroups:
    - llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openmodels
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-inference-llmaz-io-v1alpha1-playground
  failurePolicy: Fail
  name: vplayground.kb.io
  rules:
  - apiGroups:
    - inference.llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - playgrounds
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-inference-llmaz-io-v1alpha1-service
  failurePolicy: Fail
  name: vservice.kb.io
  rules:
  - apiGroups:
    - inference.llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: None
