---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-llmaz-io-v1alpha1-model
  failurePolicy: Fail
  name: mmodel.kb.io
  rules:
  - apiGroups:
    - llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - models
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-inference-llmaz-io-v1alpha1-playground
  failurePolicy: Fail
  name: mplayground.kb.io
  rules:
  - apiGroups:
    - inference.llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - playgrounds
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-llmaz-io-v1alpha1-model
  failurePolicy: Fail
  name: vmodel.kb.io
  rules:
  - apiGroups:
    - llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - models
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-inference-llmaz-io-v1alpha1-playground
  failurePolicy: Fail
  name: vplayground.kb.io
  rules:
  - apiGroups:
    - inference.llmaz.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - playgrounds
  sideEffects: None
