# permissions for end users to edit backendruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backendruntime-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: llmaz
    app.kubernetes.io/part-of: llmaz
    app.kubernetes.io/managed-by: kustomize
  name: backendruntime-editor-role
rules:
- apiGroups:
  - inference.llmaz.io
  resources:
  - backendruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.llmaz.io
  resources:
  - backendruntimes/status
  verbs:
  - get
