# permissions for end users to view playgrounds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: playground-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: llmaz
    app.kubernetes.io/part-of: llmaz
    app.kubernetes.io/managed-by: kustomize
  name: playground-viewer-role
rules:
- apiGroups:
  - inference.llmaz.io
  resources:
  - playgrounds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inference.llmaz.io
  resources:
  - playgrounds/status
  verbs:
  - get
