---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - inference.llmaz.io
  resources:
  - playgrounds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.llmaz.io
  resources:
  - playgrounds/finalizers
  verbs:
  - update
- apiGroups:
  - inference.llmaz.io
  resources:
  - playgrounds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inference.llmaz.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.llmaz.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - inference.llmaz.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - llmaz.io
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llmaz.io
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - llmaz.io
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
