---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - llmaz.inftyai.io
  resources:
  - inferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llmaz.inftyai.io
  resources:
  - inferences/finalizers
  verbs:
  - update
- apiGroups:
  - llmaz.inftyai.io
  resources:
  - inferences/status
  verbs:
  - get
  - patch
  - update
