apiVersion: inference.llmaz.io/v1alpha1
kind: Playground
metadata:
  name: qwen2-0--5b
spec:
  replicas: 1
  modelClaim:
    modelName: qwen2-0--5b-gguf
  backendConfig:
    name: llamacpp
    args:
    - -fa # use flash attention
