apiVersion: inference.llmaz.io/v1alpha1
kind: Playground
metadata:
  labels:
    app.kubernetes.io/name: playground
    app.kubernetes.io/instance: playground-sample
    app.kubernetes.io/part-of: llmaz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: llmaz
  name: playground-llama3-8b
spec:
  replicas: 1
  modelClaim:
    modelName: "llama3-8b"
