apiVersion: inference.llmaz.io/v1alpha1
kind: Playground
metadata:
  name: opt-125m
spec:
  replicas: 1
  modelClaim:
    modelName: opt-125m
  backendConfig:
    name: sglang # Current support includes VLLM and SGLANG. More backends will be added in the future.
    version: v0.2.9-cu121