apiVersion: llmaz.io/v1alpha1
kind: OpenModel
metadata:
  name: opt-125m
spec:
  familyName: opt
  source:
    modelHub:
      name: ModelScope
      modelID: AI-ModelScope/opt-125
  inferenceConfig:
    flavors:
      - name: t4 # GPU type
        requests:
          nvidia.com/gpu: 1
