apiVersion: llmaz.io/v1alpha1
kind: OpenModel
metadata:
  name: qwen2-0--5b-instruct
spec:
  familyName: qwen2
  source:
    uri: host:///workspace/Qwen2-0.5B-Instruct
  inferenceConfig:
    flavors:
      - name: t4 # GPU type
        requests:
          nvidia.com/gpu: 1
